# Generated by Django 3.1.7 on 2021-05-04 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_empresa_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=1000)),
                ('fecha_apertura', models.DateField()),
                ('fecha_resolucion', models.DateField()),
                ('nivel_urgencia', models.CharField(max_length=50)),
                ('tipo_ticket', models.CharField(max_length=50)),
                ('estado_ticket', models.CharField(max_length=50)),
                ('comentario', models.TextField(max_length=1000)),
                ('FK_Empleado_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.empleado')),
            ],
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='red',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='votes',
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_adquisicion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_puestaenmarcha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='planta',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='proveedor_nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipoequipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Red',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
        migrations.AddField(
            model_name='ticket',
            name='FK_Equipo_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipo'),
        ),
    ]
