# Generated by Django 3.1.7 on 2021-05-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210504_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='numerodeserie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='proveedor_tlf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='numeroreferencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='planta',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='proveedor_nombre',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipoequipo',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
