# Generated by Django 3.2 on 2021-05-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210507_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='fecha_puesta_en_marcha',
            new_name='fecha_puestaenmarcha',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='numero_de_serie',
            new_name='numerodeserie',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='tipo_equipo',
            new_name='tipoequipo',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='numero_referencia',
            new_name='numeroreferencia',
        ),
    ]
