# Generated by Django 3.2 on 2021-05-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210507_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='fecha_puestaenmarcha',
            new_name='fecha_puesta_en_marcha',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='numerodeserie',
            new_name='numero_de_serie',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='tipoequipo',
            new_name='tipo_equipo',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='numeroreferencia',
            new_name='numero_referencia',
        ),
    ]
